RegisterCommand(Config.commandName, function(source, args, rawCommand) TriggerClientEvent("delallveh", -1) end, Config.restricCommand)

function CleanUpCronTask(d, h, m)
  TriggerClientEvent("delallveh", -1)
end


TriggerEvent('cron:runAt', 0, 55, CleanUpCronTask) -- time to run
TriggerEvent('cron:runAt', 1, 55, CleanUpCronTask)     
TriggerEvent('cron:runAt', 2, 55, CleanUpCronTask)    
TriggerEvent('cron:runAt', 3, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 4, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 5, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 6, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 7, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 8, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 9, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 10, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 11, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 12, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 13, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 14, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 15, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 16, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 17, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 18, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 19, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 20, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 21, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 22, 55, CleanUpCronTask)
TriggerEvent('cron:runAt', 23, 55, CleanUpCronTask)